[package]
name = "ylong_ffrt"
version = "1.0.0"
edition = "2021"
description = "FFRT adapter"
license = "Apache-2.0"
repository = "https://gitee.com/openharmony/commonlibrary_rust_ylong_runtime"
keywords = ["ylong", "ffrt"]

[dependencies]
libc = "0.2.134"
